import AicsLogoSVGAsset from "./AICS-logo.svg?react";
import AicsLogoAndNameSVGAsset from "./AICS-logo-and-name.svg?react";
import DropdownSVGAsset from "./dropdown-arrow.svg?react";
import BarChartSlashIconSVGAsset from "./icon-bar-chart-slash.svg?react";
import CentroidIconSVGAsset from "./icon-centroid.svg?react";
import CentroidSlashIconSVGAsset from "./icon-centroid-slash.svg?react";
import HeatmapIconSVGAsset from "./icon-heatmap.svg?react";
import HeatmapSlashIconSVGAsset from "./icon-heatmap-slash.svg?react";
import ImageIconSVGAsset from "./icon-image.svg?react";
import ImageSlashIconSVGAsset from "./icon-image-slash.svg?react";
import ImagesIconSVGAsset from "./icon-images.svg?react";
import ImagesSlashIconSVGAsset from "./icon-images-slash.svg?react";
import ResetViewIconSVGAsset from "./icon-reset-view.svg?react";
import SwitchIconSVGAsset from "./icon-switch-arrows.svg?react";
import TagIconSVGAsset from "./icon-tag.svg?react";
import TagAddIconSVGAsset from "./icon-tag-add.svg?react";
import TagSlashIconSVGAsset from "./icon-tag-slash.svg?react";
import NoImageSVGAsset from "./no-image.svg?react";
import SpinBoxHandleDownSVGAsset from "./spin_box-handle-down.svg?react";
import SpinBoxHandleUpSVGAsset from "./spin_box-handle-up.svg?react";

export const AicsLogoAndNameSVG = AicsLogoAndNameSVGAsset;
export const AicsLogoSVG = AicsLogoSVGAsset;
export const BarChartSlashIconSVG = BarChartSlashIconSVGAsset;
export const DropdownSVG = DropdownSVGAsset;
export const SwitchIconSVG = SwitchIconSVGAsset;
export const NoImageSVG = NoImageSVGAsset;
export const HeatmapIconSVG = HeatmapIconSVGAsset;
export const HeatmapSlashIconSVG = HeatmapSlashIconSVGAsset;
export const ImagesIconSVG = ImagesIconSVGAsset;
export const ImagesSlashIconSVG = ImagesSlashIconSVGAsset;
export const TagIconSVG = TagIconSVGAsset;
export const TagSlashIconSVG = TagSlashIconSVGAsset;
export const TagAddIconSVG = TagAddIconSVGAsset;
export const SpinBoxHandleDownSVG = SpinBoxHandleDownSVGAsset;
export const SpinBoxHandleUpSVG = SpinBoxHandleUpSVGAsset;
export const CentroidIconSVG = CentroidIconSVGAsset;
export const CentroidSlashIconSVG = CentroidSlashIconSVGAsset;
export const ResetViewIconSVG = ResetViewIconSVGAsset;
export const ImageIconSVG = ImageIconSVGAsset;
export const ImageSlashIconSVG = ImageSlashIconSVGAsset;
