import AicsLogoSVGAsset from "./AICS-logo.svg?react";
import AicsLogoAndNameSVGAsset from "./AICS-logo-and-name.svg?react";
import DropdownSVGAsset from "./dropdown-arrow.svg?react";
import ExportIconSVGAsset from "./icon-export.svg?react";
import ImagesIconSVGAsset from "./icon-images.svg?react";
import ImagesSlashIconSVGAsset from "./icon-images-slash.svg?react";
import SwitchIconSVGAsset from "./icon-switch-arrows.svg?react";
import TagIconSVGAsset from "./icon-tag.svg?react";
import TagAddIconSVGAsset from "./icon-tag-add.svg?react";
import TagSlashIconSVGAsset from "./icon-tag-slash.svg?react";
import NoImageSVGAsset from "./no-image.svg?react";
import SpinBoxHandleDownSVGAsset from "./spin_box-handle-down.svg?react";
import SpinBoxHandleUpSVGAsset from "./spin_box-handle-up.svg?react";

export const AicsLogoAndNameSVG = AicsLogoAndNameSVGAsset;
export const AicsLogoSVG = AicsLogoSVGAsset;
export const DropdownSVG = DropdownSVGAsset;
export const SwitchIconSVG = SwitchIconSVGAsset;
export const NoImageSVG = NoImageSVGAsset;
export const ImagesIconSVG = ImagesIconSVGAsset;
export const ImagesSlashIconSVG = ImagesSlashIconSVGAsset;
export const TagIconSVG = TagIconSVGAsset;
export const TagSlashIconSVG = TagSlashIconSVGAsset;
export const TagAddIconSVG = TagAddIconSVGAsset;
export const ExportIconSVG = ExportIconSVGAsset;
export const SpinBoxHandleDownSVG = SpinBoxHandleDownSVGAsset;
export const SpinBoxHandleUpSVG = SpinBoxHandleUpSVGAsset;
