import type { RenderCanvasStateParams } from "src/colorizer/viewport/types";
import type { ViewerStoreState } from "src/state/slices";

export const renderCanvasStateParamsSelector = (state: ViewerStoreState): RenderCanvasStateParams => ({
  dataset: state.dataset,
  collection: state.collection,
  datasetKey: state.datasetKey,
  featureKey: state.featureKey,
  pendingFrame: state.pendingFrame,
  track: state.track,
  viewMode: state.viewMode,
  tracks: state.tracks,
  isSelectedLut: state.isSelectedLut,
  showTrackPath: state.showTrackPath,
  showTrackPathBreaks: state.showTrackPathBreaks,
  colorRamp: state.colorRamp,
  colorRampRange: state.colorRampRange,
  categoricalPaletteRamp: state.categoricalPaletteRamp,
  outlineColor: state.outlineColor,
  edgeColor: state.edgeColor,
  edgeMode: state.edgeMode,
  edgeColorAlpha: state.edgeColorAlpha,
  trackPathColor: state.trackPathColor,
  trackPathColorRamp: state.trackPathColorRamp,
  trackPathWidthPx: state.trackPathWidthPx,
  trackPathColorMode: state.trackPathColorMode,
  trackPathPastSteps: state.trackPathPastSteps,
  trackPathFutureSteps: state.trackPathFutureSteps,
  showAllTrackPathPastSteps: state.showAllTrackPathPastSteps,
  showAllTrackPathFutureSteps: state.showAllTrackPathFutureSteps,
  persistTrackPathWhenOutOfRange: state.persistTrackPathWhenOutOfRange,
  outlierDrawSettings: state.outlierDrawSettings,
  outOfRangeDrawSettings: state.outOfRangeDrawSettings,
  inRangeLUT: state.inRangeLUT,
  vectorMotionDeltas: state.vectorMotionDeltas,
  vectorVisible: state.vectorVisible,
  vectorColor: state.vectorColor,
  vectorScaleFactor: state.vectorScaleFactor,
  vectorScaleThicknessByMagnitude: state.vectorScaleThicknessByMagnitude,
  vectorThickness: state.vectorThickness,
  backdropKey: state.backdropKey,
  backdropVisible: state.backdropVisible,
  channelSettings: state.channelSettings,
  objectOpacity: state.objectOpacity,
  backdropSaturation: state.backdropSaturation,
  backdropBrightness: state.backdropBrightness,
  interpolate3d: state.interpolate3d,
});
