import { RenderCanvasStateParams } from "@/colorizer/IRenderCanvas";
import { ViewerStoreState } from "@/state/slices";

export const renderCanvasStateParamsSelector = (state: ViewerStoreState): RenderCanvasStateParams => ({
  dataset: state.dataset,
  collection: state.collection,
  datasetKey: state.datasetKey,
  featureKey: state.featureKey,
  pendingFrame: state.pendingFrame,
  track: state.track,
  showTrackPath: state.showTrackPath,
  showTrackPathBreaks: state.showTrackPathBreaks,
  colorRamp: state.colorRamp,
  colorRampRange: state.colorRampRange,
  categoricalPaletteRamp: state.categoricalPaletteRamp,
  outlineColor: state.outlineColor,
  edgeColor: state.edgeColor,
  edgeMode: state.edgeMode,
  edgeColorAlpha: state.edgeColorAlpha,
  trackPathColor: state.trackPathColor,
  trackPathWidthPx: state.trackPathWidthPx,
  trackPathColorMode: state.trackPathColorMode,
  outlierDrawSettings: state.outlierDrawSettings,
  outOfRangeDrawSettings: state.outOfRangeDrawSettings,
  inRangeLUT: state.inRangeLUT,
  vectorMotionDeltas: state.vectorMotionDeltas,
  vectorVisible: state.vectorVisible,
  vectorColor: state.vectorColor,
  vectorScaleFactor: state.vectorScaleFactor,
  backdropKey: state.backdropKey,
  backdropVisible: state.backdropVisible,
  channelSettings: state.channelSettings,
  objectOpacity: state.objectOpacity,
  backdropSaturation: state.backdropSaturation,
  backdropBrightness: state.backdropBrightness,
});
