# Adapted from https://github.com/marketplace/actions/deploy-pr-preview.
name: Deploy PR Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}
permissions: {}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    needs: [deploy-preview-internal]
    permissions:
      pull-requests: write # Required to comment on PR with preview link
      contents: write # Required for pushing to gh-pages branch

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6.0.0
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      # Must override default vite build base so that assets can still be accessed
      # when not placed in the root directory of gh-pages branch.
      - name: Build
        run: npx vite build --base=/${GITHUB_EVENT_REPOSITORY_NAME}/pr-preview/pr-${{ github.event.number }}/
        env:
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@430e3dfc1de8a8ae77e77d862d25676ef9db55d1 #v1.4.8
        with:
          source-dir: ./dist/

  deploy-preview-internal:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to comment on PR with preview link
      contents: write # Required for pushing to gh-pages branch

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6.0.0
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npx vite build --base=/${GITHUB_EVENT_REPOSITORY_NAME}/pr-preview-internal/pr-${{ github.event.number }}/ --config config/vite.internal-build.config.js
        env:
          GITHUB_EVENT_REPOSITORY_NAME: ${{ github.event.repository.name }}

      - name: Deploy internal preview
        uses: rossjrw/pr-preview-action@430e3dfc1de8a8ae77e77d862d25676ef9db55d1 #v1.4.8
        with:
          source-dir: ./dist/
          umbrella-dir: pr-preview-internal
