name: Create release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 #v3.6.0
        with:
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v6.0.0
        with:
          node-version: "22"
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false # Do not cache when publishing to prevent cache pollution attacks

      # Adapted from AGAVE.
      # Since Github actions (currently) doesn't provide a slugged version of the git tag we have to
      # create it by ourselves. It is then made available to other steps in this job as a step.outputs
      # variable.
      - name: Get the version (git tag)
        id: get_version
        run: |
          echo ${GITHUB_REF/refs\/tags\/v/}
          echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Rename build folder
        run: mv dist viewer

      - name: Zip build artifact
        run: zip -r tfe-${VERSION_TAG}.zip viewer/*
        env:
          VERSION_TAG: ${{ steps.get_version.outputs.VERSION }}

      - name: Create release
        run: gh release create ${VERSION_TAG} --draft tfe-${VERSION_TAG}.zip
        env:
          VERSION_TAG: ${{ steps.get_version.outputs.VERSION }}
